<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>741b6a0c-fdf2-49e6-936e-e1a021ee9458</testSuiteGuid>
   <testCaseLink>
      <guid>7aea1cc5-427b-4a07-a97f-805315a366ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Web Application/Data Driven Test case FOR LOOP</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>fdfda4ea-59c8-4fb4-aa7d-3c4093a07acb</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login Test Data/Demo Account</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fce98b0-8ab8-451d-a18d-9f7ae6fd520f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae1da9f3-dfc2-47bb-8485-2b1a858f44e4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
