<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Choose-date</name>
   <tag></tag>
   <elementGuidId>ffb9dd37-6dfb-473e-b4d2-00a5721ba090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;chooseDateForm&quot;)/fieldset[1]/ol[1]/li[1]/a[@class=&quot;dp-choose-date&quot;][count(. | //a[@href = '#' and @class = 'dp-choose-date' and @title = 'Choose date' and (text() = 'Choose date' or . = 'Choose date')]) = count(//a[@href = '#' and @class = 'dp-choose-date' and @title = 'Choose date' and (text() = 'Choose date' or . = 'Choose date')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dp-choose-date</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Choose date</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose date</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chooseDateForm&quot;)/fieldset[1]/ol[1]/li[1]/a[@class=&quot;dp-choose-date&quot;]</value>
   </webElementProperties>
</WebElementEntity>
